print('Test Code 1')
print('How many revisions have been made?')
num = input()
print(str(num) + ' revisions have been made')
#print('Changed by johnsondjj using new branch')
print('user johnsondjj and branch johnsondjj')
